#Felipe Bueno de Oliveira
### Verbo GET - listar todos os funcionários
GET http://localhost:8000/funcionario/ HTTP/1.1

### Verbo GET - listar um 
GET http://localhost:8000/funcionario/10 HTTP/1.1

### Verbo POST - Adicionar
POST http://127.0.0.1:8000/funcionario/ HTTP/1.1
Content-Type: application/json

{
    "nome": "Felipe Bueno",
    "matricula": "151656",
    "cpf": "1",
    "telefone": "tel23456789",
    "grpo": 1,
    "senha": "123456abc"
}


### Verbo PUT - Atualizar
PUT http://127.0.0.1:8000/funcionario/2 HTTP/1.1
Content-Type: application/json

{
    "nome": "Felipe Bueno",
    "matricula": "fe656",
    "cpf": "1",
    "telefone": "tel23456789",
    "grpo": 1,
    "senha": "abc123456"
}
### Verbo DELETE - Excluir
DELETE http://127.0.0.1:8000/funcionario/3 HTTP/1.1